networks:
  internalnetwork: {}
services:
  cardsinitial:
    environment:
    - INITIAL_SLING_NODE=true
    - CARDS_RELOAD=${CARDS_RELOAD:-}
    - OAK_FILESYSTEM=true
    image: cards/cards:latest
    networks:
      internalnetwork:
        aliases:
        - cardsinitial
    ports:
    - 8080:8080
  ldap:
    image: dwimberger/ldap-ad-it
    networks:
     internalnetwork:
       aliases:
       - ldapmock
version: '3'
volumes: {}
