name: 'Build postfix-docker'
description: 'Builds the postfix-docker image for CARDS SMTPS testing'
runs:
  using: "composite"
  steps:
    - name: Build postfix-docker
      run: |
        echo "::group::Build postfix-docker"
        cd Utilities/Development/EmailServer
        docker build -t cards/postfix-docker .
        echo "::endgroup::"
      shell: bash
